spring.datasource.url=jdbc:oracle:thin:@d15ax99a1ecxjr50_high?TNS_ADMIN=/app/wallet
spring.datasource.username=Admin
spring.datasource.password=Password1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
