spring.datasource.url=jdbc:oracle:thin:@d15ax99a1ecxjr50_high?TNS_ADMIN=/app/wallet
spring.datasource.username=Admin
spring.datasource.password=Password1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

cloud.aws.s3.bucket=sistema-inscripciones

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
cloud.aws.credentials.access-key=TU_ACCESS_KEY
cloud.aws.credentials.secret-key=TU_SECRET_KEY
cloud.aws.credentials.session-token=TU_SESSION_TOKEN

cloud.aws.region.static=us-east-1

server.port=8080
